CREATE DATABASE CRUDDATABASEJAVA;
USE CRUDDATABASEJAVA;
CREATE TABLE PEOPLE (
    PEOID INT (6) UNSIGNED AUTO_INCREMENT,
    PEONAME VARCHAR (50) NOT NULL,
    PEOCITY VARCHAR (30) NOT NULL,
    PEOPHONE VARCHAR (15),
    PRIMARY KEY (PEOID)
); 
SHOW TABLES;
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Juan Pérez', 'Bogotá', '3001234567');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('María Gómez', 'Medellín', '3107654321');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Carlos Ruiz', 'Cali', '3014567890');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Laura Torres', 'Barranquilla', '3021112233');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Andrés Ríos', 'Cartagena', '3049988776');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Sofía Moreno', 'Bucaramanga', '3112233445');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Diego Fernández', 'Pereira', '3124561234');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Camila Jiménez', 'Manizales', '3137896543');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Felipe Romero', 'Cúcuta', '3148763452');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Daniela Castro', 'Ibagué', '3203345566');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Luis Vargas', 'Neiva', '3214456677');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Paula Duarte', 'Santa Marta', '3225567788');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Tomás Martínez', 'Villavicencio', '3236678899');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Valentina Reyes', 'Montería', '3247788990');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Esteban López', 'Armenia', '3258899001');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Isabela Salazar', 'Popayán', '3269900112');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Mateo Hernández', 'Sincelejo', '3271011223');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Lucía Pineda', 'Tunja', '3282122334');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Santiago Silva', 'Palmira', '3293233445');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Gabriela Cárdenas', 'Floridablanca', '3304344556');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Alejandro Ortiz', 'Soledad', '3315455667');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Natalia Mendoza', 'Riohacha', '3326566778');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Sebastián Guerrero', 'Tuluá', '3337677889');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Mariana Lozano', 'Yopal', '3348788990');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Julián Navarro', 'Quibdó', '3359899001');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Emilia Peña', 'Buenaventura', '3360900112');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('David Castillo', 'Zipaquirá', '3371011223');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Renata Rincón', 'Chía', '3382122334');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Samuel Barreto', 'Fusagasugá', '3393233445');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Antonella Arias', 'Girardot', '3404344556');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Manuel Páez', 'Ipiales', '3415455667');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Julieta Hoyos', 'Rionegro', '3426566778');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Agustín Vargas', 'Facatativá', '3437677889');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Emma León', 'Maicao', '3448788990');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Pablo Gaitán', 'La Dorada', '3459899001');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Mía Castaño', 'Duitama', '3460900112');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Bruno Salcedo', 'Sogamoso', '3471011223');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Victoria Molina', 'Ocaña', '3482122334');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Isaac Ayala', 'Turbo', '3493233445');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Zoe Londoño', 'Pitalito', '3504344556');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Leonardo Parra', 'San Andrés', '3515455667');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Ariana Medina', 'Leticia', '3526566778');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Martín Méndez', 'Apartadó', '3537677889');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Abril Niño', 'Cartago', '3548788990');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Benjamín Villalba', 'Ciénaga', '3559899001');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Amanda Solano', 'Lorica', '3560900112');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Elías Andrade', 'El Banco', '3571011223');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Martina Cobo', 'Tumaco', '3582122334');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Thiago Fajardo', 'Jamundí', '3593233445');
INSERT INTO PEOPLE (PEONAME, PEOCITY, PEOPHONE) VALUES ('Luna Mejía', 'Puerto Asís', '3604344556');