CREATE DATABASE APICRUD;
USE APICRUD;
CREATE TABLE APIUSER (
    APIID INT (6) UNSIGNED AUTO_INCREMENT,
    APINAME VARCHAR (20),
    APIAGE INT (100),
    APICOUNTRY VARCHAR (20),
    PRIMARY KEY (APIID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = UTF8;