CREATE DATABASE IF NOT EXISTS CRUDDATABASEJAVA;
USE CRUDDATABASEJAVA;
CREATE TABLE IF NOT EXISTS PEOPLE (
    PEOID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PEONAME VARCHAR (255) NOT NULL,
    PEOCITY VARCHAR (255) NOT NULL,
    PEOPHONE VARCHAR (20) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--- En caso de querer eliminar la base de datos, 
--- se puede usar el siguiente comando:
DROP DATABASE IF EXISTS CRUDDATABASEJAVA;